openapi: 3.1.0
info:
  title: i.AI Consultation analyser
  version: v0.1
paths:
  /:
    get:
      responses:
        '200':
          description: Successful operation
components:
  schemas:
    Consultation:
      type: object
      description: Consultation is the top-level object describing a consultation. It contains one or more Sections, which in turn contain Questions.
      additionalProperties: false
      required:
        - name
        - sections
      properties:
        name:
          type: string
          description: The name of the consultation
          examples:
            - 'Consultation on Kit Kats'
            - 'How should Kit Kats change'
            - 'What shall we do about Kit Kats'
        sections:
          type: array
          minItems: 1
          description: The sections of the consultation
          items:
            $ref: '#/components/schemas/Section'
    Section:
      type: object
      description: A Section contains a group of Questions. Consultations that do not have multiple sections should group all Questions under a single Section.
      additionalProperties: false
      required:
        - name
        - questions
      properties:
        name:
          type: string
          description: The name of the section
          examples:
            - 'When to enforce a Kit Kat ban'
            - 'When to encourage the eating of Kit Kats'
            - 'When Kit Kats are consumed'
        questions:
          type: array
          minItems: 1
          description: The questions in the consultation
          items:
            $ref: '#/components/schemas/Question'
    Question:
      type: object
      description: |
        Questions can be free text, multiple choice or both. The presence of multiple_choice_options implies that the question has a multiple choice part.
      required:
        - id
        - text
        - has_free_text
      additionalProperties: false
      properties:
        id:
          type: string
          examples:
          - '1'
          - '2'
          - '3'
          - 'vii'
          - 'Question 1'
          - 'q1.2'
          description: The number or other unique identifier for this question
        text:
          type: string
          description: The question text
          examples:
            - 'Should it happen on Tuesdays?'
            - 'Should it happen in the month of May?'
            - 'Should it happen on a full moon?'
            - 'Should it happen on Fridays?'
            - 'Should it be forbidden on Sunday?'
        has_free_text:
          type: boolean
          description: Does this question have a free text component?
        multiple_choice:
          $ref: '#/components/schemas/MultipleChoice'
    Answer:
      type: object
      description: Each Answer is associated with a Question and belongs to a ConsultationResponse.
      required:
        - question_id
      additionalProperties: false
      properties:
        question_id:
          type: string
          examples:
          - '1'
          - '2'
          - '3'
          - 'vii'
          - 'Question 1'
          - 'q1.2'
          description: The number or other unique identifier for the answered question
        multiple_choice:
          $ref: '#/components/schemas/MultipleChoice'
        free_text:
          type: string
          description: The answer to the free text part of the question, if any
          examples:
            - I don't think this is a good idea at all
            - I would like to point out a few things
            - I would like clarification on a few key points
    MultipleChoice:
      type: array
      description: A list of multiple choice questions with arrays of options or arrays of answers
      items:
        type: object
        description: A multiple choice question and its available (or selected, according to context) options
        required:
          - question_text
          - options
        properties:
          question_text:
            type: string
          options:
            type: array
            items:
              type: string
            uniqueItems: true
    ConsultationResponse:
      type: object
      description: A ConsultationResponse groups answers. For now it is also a placeholder for response-level information such as demographics, responding-in-the-capacity-of, etc.
      required:
        - answers
        - submitted_at
        - id
      additionalProperties: false
      properties:
        submitted_at:
          type: string
          format: date-time
          description: The submission date and time of the response
        answers:
          type: array
          minItems: 1
          description: The answers in this response
          items:
            $ref: '#/components/schemas/Answer'
    ConsultationWithResponses:
      type: object
      description: A Consultation and its ConsultationResponses
      required:
        - consultation
        - consultation_responses
      additionalProperties: false
      properties:
        consultation:
          type: object
          description: The consultation
          $ref: '#/components/schemas/Consultation'
        consultation_responses:
          type: array
          minItems: 1
          description: The responses
          items:
            $ref: '#/components/schemas/ConsultationResponse'

