openapi: 3.1.0
info:
  title: i.AI Consult
  version: v0.1
paths:
  /:
    get:
      responses:
        '200':
          description: Successful operation
components:
  schemas:
    Consultation:
      type: object
      description: Consultation is the top-level object describing a consultation. It contains one or more Sections, which in turn contain Questions.
      additionalProperties: false
      required:
        - name
        - sections
      properties:
        name:
          type: string
          description: The name of the consultation
          examples:
            - 'Consultation on Kit Kats'
            - 'How should Kit Kats change'
            - 'What shall we do about Kit Kats'
        sections:
          type: array
          minItems: 1
          description: The sections of the consultation
          items:
            $ref: '#/components/schemas/Section'
    Section:
      type: object
      description: A Section contains a group of Questions. Consultations that do not have multiple sections should group all Questions under a single Section.
      additionalProperties: false
      required:
        - name
        - questions
      properties:
        name:
          type: string
          description: The name of the section
          examples:
            - 'When to enforce a Kit Kat ban'
            - 'When to encourage the eating of Kit Kats'
            - 'When Kit Kats are consumed'
        questions:
          type: array
          minItems: 1
          description: The questions in the consultation
          items:
            $ref: '#/components/schemas/Question'
    Question:
      type: object
      description: |
        Questions can be free text, multiple choice or both. The presence of multiple_choice_options implies that the question has a multiple choice part.
      required:
        - id
        - text
        - has_free_text
      additionalProperties: false
      properties:
        id:
          type: string
          examples:
          - '1'
          - '2'
          - '3'
          - 'vii'
          - 'Question 1'
          - 'q1.2'
          description: The number or other unique identifier for this question
        text:
          type: string
          description: The question text
          examples:
            - 'Should it happen on Tuesdays?'
            - 'Should it happen in the month of May?'
            - 'Should it happen on a full moon?'
            - 'Should it happen on Fridays?'
            - 'Should it be forbidden on Sunday?'
        has_free_text:
          type: boolean
          description: Does this question have a free text component?
        multiple_choice:
          $ref: '#/components/schemas/MultipleChoice'
    Answer:
      type: object
      description: Each Answer is associated with a Question and belongs to a ConsultationResponse.
      required:
        - question_id
      additionalProperties: false
      properties:
        question_id:
          type: string
          examples:
          - '1'
          - '2'
          - '3'
          - 'vii'
          - 'Question 1'
          - 'q1.2'
          description: The number or other unique identifier for the answered question
        theme_id:
          type: string
          format: uuid
          description: The associated Theme, if any. Omit if uploading.
        multiple_choice:
          $ref: '#/components/schemas/MultipleChoice'
        free_text:
          type: string
          description: The answer to the free text part of the question, if any
          examples:
            - I don't think this is a good idea at all
            - I would like to point out a few things
            - I would like clarification on a few key points
    MultipleChoice:
      type: array
      description: A list of multiple choice questions with arrays of options or arrays of answers
      items:
        type: object
        description: A multiple choice question and its available (or selected, according to context) options
        required:
          - question_text
          - options
        properties:
          question_text:
            type: string
          options:
            type: array
            items:
              type: string
            uniqueItems: true
    ConsultationResponse:
      type: object
      description: A ConsultationResponse groups answers. For now it is also a placeholder for response-level information such as demographics, responding-in-the-capacity-of, etc.
      required:
        - answers
        - submitted_at
        - id
      additionalProperties: false
      properties:
        id:
          type: string
          format: uuid
        submitted_at:
          type: string
          format: date-time
          description: The submission date and time of the response
        answers:
          type: array
          minItems: 1
          description: The answers in this response
          items:
            $ref: '#/components/schemas/Answer'
    ConsultationWithResponses:
      type: object
      description: A Consultation and its ConsultationResponses
      required:
        - consultation
        - consultation_responses
      additionalProperties: false
      properties:
        consultation:
          type: object
          description: The consultation
          $ref: '#/components/schemas/Consultation'
        consultation_responses:
          type: array
          minItems: 1
          description: The responses
          items:
            $ref: '#/components/schemas/ConsultationResponse'
    ConsultationWithResponsesAndThemes:
      type: object
      description: |
        A Consultation and its ConsultationResponses, plus Themes assigned by
        the tool and metadata about the processing run
      required:
        - consultation
        - consultation_responses
        - themes
        - processing
      additionalProperties: false
      properties:
        consultation:
          type: object
          description: The consultation
          $ref: '#/components/schemas/Consultation'
        consultation_responses:
          type: array
          minItems: 1
          description: The responses
          items:
            $ref: '#/components/schemas/ConsultationResponse'
        themes:
          type: array
          minItems: 1
          description: The themes
          items:
            $ref: '#/components/schemas/Theme'
        processing:
          type: object
          description: How this consultation was processed
          $ref: '#/components/schemas/Processing'
    Theme:
      type: object
      description: A theme, assigned by AI
      required:
        - id
        - topic_id
        - topic_keywords
        - summary
        - short_description
      additionalProperties: false
      properties:
        id:
          type: string
          format: uuid
        topic_id:
          type: integer
        topic_keywords:
          type: array
          description: The keywords in the theme
          items:
            type: string
            examples:
              - birds
              - animals
              - food
              - rivers
              - economy
              - lakes
              - farming
        short_description:
          type: string
          examples:
            - Concern about the price of sugar
            - Risk to wildlife habitats
            - Overall quality of outdoor space in the area
        summary:
          type: string
          description: A free-text summary of the theme
          examples:
            - Respondents identified potential impact on the price of sugar,
              noting that proposed new legislation was very likely to drive it
              higher
            - Respondents flagged concerns around the conservation of habitats
              in the area and local biodiversity in general
    LLM:
      type: object
      required:
        - prompt_template
        - language_model
      additionalProperties: false
      properties:
        prompt_template:
          type: string
          description: The prompt we used to generate the summaries
          examples:
            - |
              You are serving as an expert AI assisting UK government
              policy officers in analyzing public opinions on new policies.
              The topic of the new policy is {consultation_name}...
        language_model:
          type: string
          description: The LLM that generated the summaries
          examples:
            - i-dot-ai-model-mistral-7b-instruct-1
            - ollama/llama3
            - fake
    DummyTopicModel:
      type: object
    BERTopic:
      type: object
      description: Metadata about how BERTopic was configured
      required:
        - embedding_model
        - dimensionality_reduction
        - clustering
        - tokenizer
        - weighting
      additionalProperties: false
      properties:
        embedding_model:
          type: string
          description: |
            The embedding model used to convert inputs to numerical
            representations, as a huggingface SentenceTransformers identifier
          examples:
            - "thenlper/gte-small"
            - "all-mpnet-base-v2"
        dimensionality_reduction:
          type: object
          required:
            - algorithm
            - parameters
          additionalProperties: false
          properties:
            algorithm:
              type: string
              enum: ["UMAP"]
            parameters:
              type: object
              oneOf:
              - $ref: "#/components/schemas/UMAPParameters"
        clustering:
          type: object
          required:
            - algorithm
            - parameters
          properties:
            algorithm:
              type: string
              enum: ["HDBSCAN"]
            parameters:
              type: object
              oneOf:
              - $ref: "#/components/schemas/HDBSCANParameters"
        tokenizer:
          required:
            - algorithm
          additionalProperties: false
          properties:
            algorithm:
              type: string
              description: The name of the tokenizer algorithm
              examples:
                - "CountVectorizer"
        weighting:
          required:
            - algorithm
          additionalProperties: false
          properties:
            algorithm:
              type: string
              description: The name of the weighting algorithm
              examples:
                - "ClassTfidfTransformer"
    HDBSCANParameters:
      type: object
      description: Parameters to configure the HDBSCAN clustering algorithm
      required:
        - min_cluster_size
        - metric
        - cluster_selection_method
        - prediction_data
      additionalProperties: false
      properties:
        min_cluster_size:
          type: integer
          description: |
            The minimum size of clusters; single linkage splits that contain
            fewer points than this will be considered points “falling out” of a
            cluster
          examples:
            - 3
        metric:
          type: string
          description: The metric used to compute distance in the input data
          examples:
            - "euclidean"
        cluster_selection_method:
          type: string
          description: The method used to select clusters from the condensed tree.
          examples:
            - "eom"
        prediction_data:
          type: boolean
          description: |
            Whether to generate extra cached data for predicting labels or
            membership vectors for new unseen points later
    UMAPParameters:
      type: object
      description: Parameters to configure the UMAP dimensionality reduction algorithm
      required:
        - n_neighbors
        - min_dist
        - n_components
        - metric
        - random_state
      additionalProperties: false
      properties:
        n_neighbors:
          type: integer
          description: |
            This parameter controls how UMAP balances local versus global
            structure in the data. It does this by constraining the size of the
            local neighborhood UMAP will look at when attempting to learn the
            manifold structure of the data.
          examples:
            - 15
        min_dist:
          type: number
          format: float
          description: |
            The min_dist parameter controls how tightly UMAP is allowed to pack
            points together. It, quite literally, provides the minimum distance
            apart that points are allowed to be in the low dimensional
            representation
          examples:
            - 0.0
        n_components:
          type: integer
          description: The dimensionality to reduce to
          examples:
            - 5
        metric:
          type: string
          description: The metric used to compute distance in the input data
          examples:
            - "cosine"
            - "hamming"
            - "jaccard"
        random_state:
          type: integer
          description: The random seed for UMAP's stochastic algorithm
          examples:
            - 12
    ProcessingRunMetadata:
      type: object
      description: Metadata about how this consultation was processed
      required:
        - started_at
        - completed_at
        - topic_model
        - llm
      additionalProperties: false
      properties:
        started_at:
          type: string
          format: date-time
        completed_at:
          type: string
          format: date-time
        topic_model:
          type: object
          description: Details of the topic model
          oneOf:
          - $ref: "#/components/schemas/BERTopic"
          - $ref: "#/components/schemas/DummyTopicModel"
        llm:
          type: object
          description: Details of the LLM
          oneOf:
          - $ref: "#/components/schemas/LLM"

