# Put action within a raw block so that the curly bracket expressions aren't picked up by the cookiecutter
# {% raw %}

name: build
on:
  push:
    branches:
      - "**"


jobs:
  set-vars:
    runs-on: ubuntu-latest
    outputs:
      app-name: ${{ steps.export.outputs.app-name }}
      ec2-instance-type: ${{ steps.export.outputs.ec2-instance-type }}
      aws-region: ${{ steps.export.outputs.aws-region }}
      version: ${{ steps.export.outputs.version }}
      runner_label: ${{ steps.export.outputs.runner_label }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: export
        run: |
          . ./.github/.github.env
          echo "ec2-instance-type=${EC2_INSTANCE_TYPE}" >> $GITHUB_OUTPUT
          echo "app-name=${APP_NAME}" >> $GITHUB_OUTPUT
          echo "aws-region=${{ secrets.AWS_REGION }}" >> $GITHUB_OUTPUT
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "RUNNER_LABEL=self-hosted" >> $GITHUB_OUTPUT
          echo ${{ secrets.AWS_REGION }}

  build-image:
    needs:
      - set-vars
    uses: i-dot-ai/i-dot-ai-core-github-actions/.github/workflows/build-docker.yml@main
    with:
      APP_NAME: ${{ needs.set-vars.outputs.app-name }}
      AWS_REGION: ${{ needs.set-vars.outputs.aws-region }}
      RUNNER_LABEL: ${{ needs.set-vars.outputs.runner_label }}
      INFRASTRUCTURE_FOLDER: "infrastructure"
    secrets:
      AWS_GITHUBRUNNER_PAT: ${{ secrets.AWS_GITHUBRUNNER_PAT}}
      AWS_GITHUBRUNNER_PAT_USER: ${{ secrets.AWS_GITHUBRUNNER_PAT_USER }}
  
# {%- endraw %}