
name: build
on:
  push:
    branches:
      - "**"


jobs:
  set-vars:
    runs-on: ubuntu-latest
    outputs:
      app-name: ${{ steps.export.outputs.app-name }}
      ec2-instance-type: ${{ steps.export.outputs.ec2-instance-type }}
      version: ${{ steps.export.outputs.version }}
      runner_label: ${{ steps.export.outputs.runner_label }}
      environment: ${{ steps.export.outputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: export
        run: |
          . ./.github/.github.env
          echo "ec2-instance-type=${EC2_INSTANCE_TYPE}" >> $GITHUB_OUTPUT
          echo "app-name=${APP_NAME}" >> $GITHUB_OUTPUT
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "environment=${ENVIRONMENT}" >> $GITHUB_OUTPUT
          echo "RUNNER_LABEL=self-hosted" >> $GITHUB_OUTPUT

  start-runner:
        uses: i-dot-ai/i-dot-ai-core-github-actions/.github/workflows/start-runner.yml@main
        needs: set-vars
        with:
            EC2_INSTANCE_TYPE: ${{ needs.set-vars.outputs.ec2-instance-type }}
            ENVIRONMENT: ${{ needs.set-vars.outputs.environment }}
        secrets:
            AWS_GITHUBRUNNER_USER_ACCESS_KEY: ${{ secrets.AWS_GITHUBRUNNER_USER_ACCESS_KEY }}
            AWS_GITHUBRUNNER_USER_SECRET_ID: ${{ secrets.AWS_GITHUBRUNNER_USER_SECRET_ID }}
            AWS_GITHUBRUNNER_PAT: ${{ secrets.AWS_GITHUBRUNNER_PAT}}
            AWS_REGION: ${{ secrets.AWS_REGION }}

  build-image:
    needs:
      - set-vars
      - start-runner
    uses: i-dot-ai/i-dot-ai-core-github-actions/.github/workflows/build-docker.yml@add/docker-prune
    with:
      APP_NAME: ${{ needs.set-vars.outputs.app-name }}
      RUNNER_LABEL: ${{ needs.set-vars.outputs.runner_label }}
      INFRASTRUCTURE_FOLDER: "infrastructure"
    secrets:
      AWS_GITHUBRUNNER_PAT: ${{ secrets.AWS_GITHUBRUNNER_PAT}}
      AWS_GITHUBRUNNER_PAT_USER: ${{ secrets.AWS_GITHUBRUNNER_PAT_USER }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  
  test:
    runs-on: ${{ needs.set-vars.outputs.runner_label }}
    needs: 
      - set-vars
      - start-runner
      - build-image
    outputs:
      IMAGE_TAG: ${{ needs.build.outputs.IMAGE_TAG }}
    env:
      DATABASE_URL: psql://pguser:pgpass@postgres:5432/consultations_test

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: pguser
          POSTGRES_PASSWORD: pgpass
          POSTGRES_DB: consultations_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    container:
      image: $:${{ needs.build.outputs.IMAGE_TAG }}

    steps:
      - uses: actions/checkout@v4

      - name: pytest
        run:
          make docker_test

  prune-docker:
    needs:
      - set-vars
      - start-runner
      - build-image
      - test
    uses: i-dot-ai/i-dot-ai-core-github-actions/.github/workflows/prune-docker.yml@add/docker-prune


  stop-runner:
        uses: i-dot-ai/i-dot-ai-core-github-actions/.github/workflows/stop-runner.yml@main
        if: needs.start-runner.outputs.use-persisted == 0 && always()
        needs: 
            - set-vars
            - start-runner
            - build-image
            - test
            - prune-docker
        with:
            RUNNER_LABEL: ${{ needs.start-runner.outputs.label }}
            EC2_INSTANCE_ID: ${{ needs.start-runner.outputs.ec2-instance-id }}
        secrets:
            AWS_GITHUBRUNNER_USER_ACCESS_KEY: ${{ secrets.AWS_GITHUBRUNNER_USER_ACCESS_KEY }}
            AWS_GITHUBRUNNER_USER_SECRET_ID: ${{ secrets.AWS_GITHUBRUNNER_USER_SECRET_ID }}
            AWS_GITHUBRUNNER_PAT: ${{ secrets.AWS_GITHUBRUNNER_PAT}}
            AWS_REGION: ${{ secrets.AWS_REGION }}